name: Build & Deploy service

on: 
  workflow_dispatch: 
  push:
    branches: 'main'

env:
  APP_NAME: daestjebot
  APP_BASE_PATH: ~/CODE # ./{path}, app name will be added
  
jobs:
  build:
    name: Build & Test
    runs-on: self-hosted
  
    steps:
      - name: Get the repository
        uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci
      - name: Copy env file
        run: cp ~/CODE/.config/env/daestjebot.env ./.env
      - name: Build
        run: npm run build

  deploy:
    name: Deploy to the docker
    runs-on: self-hosted
    needs: build

    steps:
      - name: Prepare workdir
        run: rm -rf $APP_BASE_PATH/$APP_NAME && mkdir -p $APP_BASE_PATH/$APP_NAME
      - name: Copy files in workdir
        run: cp -r ./* ./.env $APP_BASE_PATH/$APP_NAME
      - name: Create docker image
        run: docker build -t $APP_NAME $APP_BASE_PATH/$APP_NAME
      - name: Restart compose service
        run: cd $APP_BASE_PATH && docker-compose up -d --force-recreate --renew-anon-volumes --no-deps $APP_NAME